name: Clans
main: com.Kingdoms.Clans.Clans
version: 2.0.1
commands:
  team:
    description: All team commands
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands
  t:
    description: Sends a message to team members
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands
  elo:
    description: All elo commands
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands

